# -----------------------------------------------
# vagrant.yml for VirtualBox
# -----------------------------------------------
node1:
  vm_name: node1
  mem_size: 8192
  cpus: 2
  public_ip:  192.168.56.111
  vip_ip:     192.168.56.112
  private_ip: 192.168.200.111
  u01_disk: ./node1_u01.vdi

node2:
  vm_name: node2
  mem_size: 8192
  cpus: 2
  public_ip:  192.168.56.121
  vip_ip:     192.168.56.122
  private_ip: 192.168.200.122
  u01_disk: ./node2_u01.vdi

shared:
  prefix_name:   vgtol7-rac
  # ---------------------------------------------
  domain  : localdomain
  scan_ip1: 192.168.56.115
  scan_ip2: 192.168.56.116
  scan_ip3: 192.168.56.117
  # ---------------------------------------------
  non_rotational: 'on'
  asm_disk_path:
  asm_disk_num:   4
  asm_disk_size: 20
  asm_lib_type:  'ASMLIB'
  p1_ratio:      80
  # ---------------------------------------------

env:
  provider: virtualbox
  # ---------------------------------------------
  gi_software:     LINUX.X64_193000_grid_home.zip
  db_software:     LINUX.X64_193000_db_home.zip
  # ---------------------------------------------
  root_password:   welcome1
  grid_password:   welcome1
  oracle_password: welcome1
  sys_password:    welcome1
  pdb_password:    welcome1
  # ---------------------------------------------
  ora_languages:   en,en_GB
  # ---------------------------------------------
  nomgmtdb:        true
  orestart:        false
  # ---------------------------------------------
  db_name:         DB193H1
  pdb_name:        PDB1
  db_type:         RAC
  cdb:             false
  # ---------------------------------------------


## -----------------------------------------------
## vagrant.yml for libVirt
## -----------------------------------------------
#node1:
#  vm_name: node1
#  mem_size: 8192
#  cpus: 2
#  public_ip:  192.168.125.111
#  vip_ip:     192.168.125.112
#  private_ip: 192.168.200.111
#  storage_pool_name: Vagrant_KVM_Storage
#
#node2:
#  vm_name: node2
#  mem_size: 8192
#  cpus: 2
#  public_ip:  192.168.125.121
#  vip_ip:     192.168.125.122
#  private_ip: 192.168.200.122
#  storage_pool_name: Vagrant_KVM_Storage
#
#shared:
#  prefix_name:   vgt-ol7-rac
#  # ---------------------------------------------
#  domain  : localdomain
#  scan_ip1: 192.168.125.115
#  scan_ip2: 192.168.125.116
#  scan_ip3: 192.168.125.117
#  # ---------------------------------------------
#  asm_disk_num:   4
#  asm_disk_size: 20
#  p1_ratio:      80
#  storage_pool_name: Vagrant_KVM_Storage
#  # ---------------------------------------------
#
#env:
#  provider: libvirt
#  # ---------------------------------------------
#  gi_software:     LINUX.X64_193000_grid_home.zip
#  db_software:     LINUX.X64_193000_db_home.zip
#  # ---------------------------------------------
#  root_password:   welcome1
#  grid_password:   welcome1
#  oracle_password: welcome1
#  sys_password:    welcome1
#  pdb_password:    welcome1
#  # ---------------------------------------------
#  ora_languages:   en,en_GB
#  # ---------------------------------------------
#  nomgmtdb:        true
#  orestart:        false
#  # ---------------------------------------------
#  db_name:         DB193H1
#  pdb_name:        PDB1
#  db_type:         RAC
#  cdb:             false
#  # ---------------------------------------------

